### ISSUE TITLE
[v1.10.0] Language settings & search parameter

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#575]
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/302)*

### Explanation of the feature

Changes
- new settings `localizedAttributes` and the sub-methods associated to it
- new search parameter `locales`

Usage: https://meilisearch.notion.site/v1-10-Language-settings-usage-26c5d98b553349d9abacbe7aff698e4e

### TODO

- [x] Add a new search parameter named `locales` to the `search` methods (GET and POST)
- [x] Ensure the `updateSettings` route can accept the new `localizedAttributes` setting
- [x] Create new methods `getLocalizedAttributes`, `updateLocalizedAttributes` and `resetLocalizedAttributes` corresponding to the sub settings `GET/PUT/DELETE` routes
- [x] Add tests
- [x] Add code samples for the feature:
    ```js
    search_parameter_reference_locales_1: |-
        client.index('INDEX_NAME').search('進撃の巨人', { locales: ['jpn'] })
    get_localized_attribute_settings_1: |-
        client.index('INDEX_NAME').getLocalizedAttributes()
    update_localized_attribute_settings_1: |-
        client.index('INDEX_NAME').updateLocalizedAttributes([
            { attributePatterns: ['jpn'], locales: ['*_ja'] },
        ])
    reset_localized_attribute_settings_1: |-
        client.index('INDEX_NAME').resetLocalizedAttributes()
    ```
