### ISSUE TITLE
[v1.10.0] AI-powered search changes

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-go#576]
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/302)*

### Explanation of the feature

- Rest embedder
  - Removed parameters: `query`, `inputField`, `inputType`, `pathToEmbeddings` and `embeddingObject`.
  - Replaced by `request` and `response`
  - New parameter: `headers`
- Add `url` parameter to the OpenAI embedder
- `dimensions` is now available as an optional parameter for `ollama` embedders.

Usage: https://meilisearch.notion.site/v1-10-AI-search-changes-737c9d7d010d4dd685582bf5dab579e2?pvs=74

### TODO

- [x] Rest embedder
  - [x] Remove the following parameters: `query`, `inputField`, `inputType`, `pathToEmbeddings` and `embeddingObject`.
  - [x] Add the new parameters `request`, `response` and `headers` (cf usage for more information)
- [x] Add `url` parameter to the OpenAI embedder
- [x] Add `dimensions` for Ollama embedders.
- [x] Update the tests accordingly
