### ISSUE TITLE
[v1.12.0] New index settings: `facetSearch` and `prefixSearch`

### ISSUE THREAD

**Issue by Strift** [meilisearch/meilisearch-go#595]
*Following the [changes related to Meilisearch v1.12.0 mega issue](https://github.com/meilisearch/integration-guides/issues/307)*

## Description

Add features introduced in [Meilisearch v1.12.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.12.0): the `facetSearch` and `prefixSearch` index settings.

For more information refer to the docs:
- [Facet search](https://www.meilisearch.com/docs/reference/api/settings#facet-search)
- [Prefix search](https://www.meilisearch.com/docs/reference/api/settings#prefix-search)

For reference, here is how these methods were implemented in JavaScript within [meilisearch-js](https://github.com/meilisearch/meilisearch-js):

```js
// get prefix search settings
const settings = await client.index('myIndex').getPrefixSearch()
// disable prefix search
await client.index('myIndex').updatePrefixSearch('disabled')
// reset prefix search settings
await client.index('myIndex').resetPrefixSearch()

// get facet search settings
const settings = await client.index('myIndex').getFacetSearch()
// disable facet search
await client.index('myIndex').updateFacetSearch(false)
// reset facet search settings
await client.index('myIndex').resetFacetSearch()
```

## Implementation

**Tasks:**
- [ ] Add the relevant methods to configure `facetSearch` and `prefixSearch` index settings.
- [ ] The methods associated with the `/settings` API route (to get, reset and update the settings globally) must be able to receive in the payload the new `facetSearch` and `prefixSearch` fields (in [meilisearch-js](https://github.com/meilisearch/meilisearch-js), the equivalent methods are `getSettings()`, `updateSettings()`, and `resetSettings()`)
- [ ] ⚠️ Add integration tests ⚠️
- [ ] Update the code samples in `.code-samples.meilisearch.yaml` to for the following keys, using the [same example as their curl counterpart](https://github.com/meilisearch/documentation/blob/main/.code-samples.meilisearch.yaml):
  - [ ] Add example for `get_facet_search_settings_1`
  - [ ] Add example for `update_facet_search_settings_1`
  - [ ] Add example for `reset_facet_search_settings_1`
  - [ ] Add example for `get_prefix_search_settings_1`
  - [ ] Add example for `update_prefix_search_settings_1`
  - [ ] Add example for `reset_prefix_search_settings_1`
