### ISSUE TITLE
[v1.12.0] Add methods for the batches API

### ISSUE THREAD

**Issue by Strift** [meilisearch/meilisearch-go#597]
*Following the [changes related to Meilisearch v1.12.0 mega issue](https://github.com/meilisearch/integration-guides/issues/307)*

## Description

Add a feature introduced in [Meilisearch v1.12.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.12.0): the **batches API**.

For more information refer to the docs:
- [Batches API reference](https://www.meilisearch.com/docs/reference/api/batches)

For reference, here is how this works in JavaScript using [meilisearch-js](https://github.com/meilisearch/meilisearch-js):

```js
// Get all batches
const batches = await client.getBatches();
// Get one batch by ID
const batch = client.getBatch(BATCH_UID);
```

## Tasks

- [ ] Add the relevant methods to **get one batch** and **get all batches** (in [meilisearch-js](https://github.com/meilisearch/meilisearch-js), the equivalent methods are `getBatch()` and `getBatches()`)
- [ ] ⚠️ Add integration tests ⚠️
- [ ] Update the code samples in `.code-samples.meilisearch.yaml` for the following keys, using the [same examples as their curl counterpart](https://github.com/meilisearch/documentation/blob/main/.code-samples.meilisearch.yaml):
  - [ ] Add example for `get_batch_1`
  - [ ] Add example for `get_all_batches_1`

**Comment by rakeshkumarnahak** [comment]
Hello @Strift, I would like to work on this issue. Please assign this to me.

**Comment by Strift** [comment]
Hello @rakeshkumarnahak,

Thanks for your interest!

We prefer not assigning issues, because we've met users who asked to be assigned and never came back.
This sometimes discourages other volunteer contributors from opening a PR to fix this issue.

But you are more than welcome to open a PR for this one. We will accept and merge the first PR fixing the issue (while adhering to our [contributing guidelines](https://app.slack.com/client/blob/main/CONTRIBUTING.md).)

We are looking forward to reviewing your PR 😊
